version: "2"

services:
  backup:
    build:
      context: .
    image: softonic/swarm-backup-restore
    command: sleep 100000
    volumes:
      - ./app:/app
    environment:
      - BUCKET=TO_BE_FILLED
      - REGION=TO_BE_FILLED
      - AWS_KEY_ID_SECRET=TO_BE_FILLED
      - AWS_ACCESS_KEY_SECRET=TO_BE_FILLED
      - IGNORE_STACKS=TO_BE_FILLED